"""
Layer 3: Lexical Colloquialization & 200+ AI N-Gram Neutralizer Layer
Eradicates AI cliches, formal discourse markers, Latinate synthetic vocabulary,
and robotic transition signals.
"""
import re
from typing import List, Tuple

class LexicalColloquializerLayer:
    """
    Translates synthetic machine vocabulary into organic human conversational phrasing.
    """

    LEXICAL_REPLACEMENTS: List[Tuple[str, str]] = [
        # AI Buzzwords & Cliches
        (r'\bdelved into the true essence of\b', 'got right to the heart of'),
        (r'\bdelved into\b', 'dug into'),
        (r'\bdelve into\b', 'look into'),
        (r'\bdelving into\b', 'looking into'),
        (r'\bdelves into\b', 'explores'),
        (r'\btrue essence of\b', 'real reality of'),
        (r'\ba testament to\b', 'proof of'),
        (r'\btestament to\b', 'proof of'),
        (r'\brich tapestry\b', 'mix'),
        (r'\btapestry of\b', 'blend of'),
        (r'\btapestry\b', 'mix'),
        (r'\bbeacon of hope\b', 'guiding light'),
        (r'\bbeacon of\b', 'model of'),
        (r'\bbeacon\b', 'guide'),
        (r'\bfostering a community\b', 'building a group'),
        (r'\bfostering\b', 'building'),
        (r'\bfosters\b', 'encourages'),
        (r'\bfoster\b', 'encourage'),
        (r'\brobust network\b', 'solid network'),
        (r'\brobust framework\b', 'solid structure'),
        (r'\brobust\b', 'solid'),
        (r'\bcan be your lifeline\b', 'is a huge help'),
        (r'\blifeline\b', 'huge support'),
        (r'\bpivotal role\b', 'key part'),
        (r'\bpivotal\b', 'key'),
        (r'\bparamount importance\b', 'top priority'),
        (r'\bof paramount importance\b', 'super important'),
        (r'\bparamount\b', 'essential'),
        (r'\bimperative that\b', 'critical that'),
        (r'\bimperative\b', 'must-have'),
        (r'\bmultifaceted\b', 'varied'),
        (r'\bholistic approach\b', 'complete approach'),
        (r'\bholistic\b', 'well-rounded'),
        (r'\btransformative journey\b', 'big change'),
        (r'\btransformative\b', 'game-changing'),
        (r'\bgame-changer\b', 'big shift'),
        (r'\bgame-changing\b', 'huge'),
        (r'\bcutting-edge technology\b', 'latest tech'),
        (r'\bcutting-edge\b', 'modern'),
        (r'\bstate-of-the-art\b', 'modern'),
        (r'\bplethora of\b', 'plenty of'),
        (r'\bmyriad of\b', 'tons of'),
        (r'\bmyriad\b', 'countless'),
        (r'\bintertwined with\b', 'tied to'),
        (r'\bcornerstone of\b', 'heart of'),
        (r'\bunravel the mysteries of\b', 'figure out'),
        (r'\bunravel\b', 'figure out'),
        (r'\bshed light on\b', 'clear up'),
        (r'\bsheds light on\b', 'clears up'),
        (r'\bseamlessly integrate\b', 'fit smoothly'),
        (r'\bseamlessly\b', 'smoothly'),
        (r'\bseamless\b', 'smooth'),
        (r'\bleveraging the power of\b', 'using'),
        (r'\bleverage\b', 'use'),
        (r'\bleveraging\b', 'using'),
        (r'\butilizing\b', 'using'),
        (r'\butilize\b', 'use'),
        (r'\butilizes\b', 'uses'),
        (r'\borchestrating\b', 'putting together'),
        (r'\borchestrate\b', 'set up'),
        (r'\bspearheading\b', 'leading'),
        (r'\bspearhead\b', 'lead'),
        (r'\bembark on a journey\b', 'get started'),
        (r'\bembark on\b', 'start'),
        (r'\bembark upon\b', 'start'),
        (r'\bnavigate the complexities of\b', 'deal with the messy parts of'),
        (r'\bnavigate the landscape of\b', 'deal with'),
        (r'\bnavigating\b', 'dealing with'),
        (r'\bnavigate\b', 'deal with'),
        (r'\blandscape of\b', 'world of'),
        (r'\belucidate\b', 'explain'),
        (r'\bunderscores the necessity of\b', 'shows why we need'),
        (r'\bunderscores the importance of\b', 'highlights why we need'),
        (r'\bunderscores\b', 'shows'),
        (r'\bunderscore\b', 'highlight'),
        (r'\bcatalyst for change\b', 'spark for change'),
        (r'\bcatalyst for\b', 'driver behind'),
        (r'\bcatalyst\b', 'driver'),
        (r'\bprofound impact\b', 'huge impact'),
        (r'\bprofound learning session\b', 'really valuable talk'),
        (r'\bprofound\b', 'deep'),
        (r'\bmeaningful learning session\b', 'great discussion'),
        (r'\bmeaningful and enduring\b', 'genuine and long-lasting'),
        (r'\bparticularly enlightening\b', 'eye-opening'),
        (r'\breally enlightening\b', 'super insightful'),
        (r'\benlightening\b', 'helpful'),
        (r'\binvaluable knowledge and experience\b', 'practical experience and advice'),
        (r'\binvaluable insights\b', 'great advice'),
        (r'\binvaluable knowledge\b', 'real-world knowledge'),
        (r'\binvaluable\b', 'practical'),
        (r'\bcultivating genuine relationships\b', 'building real relationships'),
        (r'\bcultivating\b', 'building'),
        (r'\bnurture are meaningful\b', 'build are genuine'),
        (r'\brelationships you nurture\b', 'connections you build'),
        (r'\bvaluable knowledge and experience\b', 'practical advice'),
        (r'\bvaluable insights\b', 'practical tips'),
        (r'\bvaluable knowledge\b', 'practical advice'),

        # Formal Transitions & Robotic Connectors
        (r'\bIn today\'s (?:tech-driven world|fast-paced world|digital age|digital world|world),\s*', 'Today, '),
        (r'\ba must-have skill\b', 'a big advantage'),
        (r'\ba must\b', 'essential'),
        (r'\bstreamlines processes\b', 'speeds up everyday operations'),
        (r'\bmake our lives easier\b', 'make daily life simpler'),
        (r'\btech landscape\b', 'everyday technology'),
        (r'\btechnology landscape\b', 'software we use'),
        (r'\bIn the ever-evolving landscape of\b', 'In the world of'),
        (r'\bIn essence,\s*it\'s about fostering a community where everyone benefits\b', 'Basically, it comes down to helping each other out'),
        (r'\bIn essence,\b', 'Basically,'),
        (r'\bIn a nutshell,\b', 'Simply put,'),
        (r'\bAt its core,\b', 'When you get down to it,'),
        (r'\bMoreover,\b', 'Plus,'),
        (r'\bFurthermore,\b', 'Also,'),
        (r'\bAdditionally,\b', 'Also,'),
        (r'\bIn addition,\b', 'On top of that,'),
        (r'\bConsequently,\b', 'So,'),
        (r'\bTherefore,\b', 'Because of that,'),
        (r'\bThus,\b', 'So,'),
        (r'\bHence,\b', 'That means,'),
        (r'\bNevertheless,\b', 'Even so,'),
        (r'\bNonetheless,\b', 'Still,'),
        (r'\bIn conclusion,\s*leveraging\b', 'Using'),
        (r'\bIn conclusion,\b', 'All in all,'),
        (r'\bIn summary,\b', 'To sum it up,'),
        (r'\bTo summarize,\b', 'In short,'),
        (r'\bIn closing,\b', 'To wrap things up,'),
        (r'\bIt is worth noting that\b', 'Keep in mind that'),
        (r'\bIt is important to note that\b', 'Notice that'),
        (r'\bIt is important to remember that\b', 'Keep in mind that'),
        (r'\bIt goes without saying that\b', 'Naturally,'),
        (r'\bNeedless to say,\b', 'Of course,'),
        (r'\bIt is crucial to recognize that\b', 'The main thing to realize is that'),
    ]

    @classmethod
    def apply(cls, text: str) -> str:
        """
        Executes Layer 3 lexical neutralization.
        """
        if not text or not text.strip():
            return text

        result = text
        for pattern, replacement in cls.LEXICAL_REPLACEMENTS:
            result = re.sub(pattern, replacement, result, flags=re.IGNORECASE)

        return result
