from app.schemas.request import ScanRequest
from langchain_ollama import ChatOllama
from langchain_core.prompts import PromptTemplate
import json
import re
import math

def calculate_burstiness(text: str) -> float:
    sentences = [s.strip() for s in re.split(r'[.?!]+', text) if s.strip()]
    if not sentences: return 0.0
    lengths = [len(s.split()) for s in sentences]
    mean = sum(lengths) / len(lengths)
    variance = sum((l - mean) ** 2 for l in lengths) / len(lengths)
    return math.sqrt(variance)

def scan_text(request: ScanRequest) -> dict:
    burstiness = calculate_burstiness(request.text)
    
    # Heuristic: high burstiness = more human
    base_human_prob = min(0.99, burstiness / 15.0)
    base_ai_prob = 1.0 - base_human_prob
    
    llm = ChatOllama(model="qwen2.5:3b", temperature=0.1, format="json")
    prompt = PromptTemplate.from_template(
        "Analyze the following text and determine the probability that it was generated by an AI. "
        "Return a JSON object with exactly one key 'ai_probability' as a float between 0.0 and 1.0.\n\n"
        "Text: {text}"
    )
    
    chain = prompt | llm
    try:
        response = chain.invoke({"text": request.text[:2000]})
        content = response.content if hasattr(response, "content") else str(response)
        data = json.loads(content)
        llm_ai_prob = float(data.get("ai_probability", 0.5))
        
        final_ai_prob = (llm_ai_prob * 0.4) + (base_ai_prob * 0.6)
        final_ai_prob = max(0.01, min(0.99, final_ai_prob))
        
        verdict = "Highly Likely AI" if final_ai_prob > 0.7 else "Mixed/Uncertain" if final_ai_prob > 0.4 else "Likely Human"
        return {
            "ai_probability": round(final_ai_prob, 2),
            "human_probability": round(1.0 - final_ai_prob, 2),
            "verdict": verdict,
            "burstiness_score": round(burstiness, 2)
        }
    except Exception as e:
        print(f"Detector error: {e}")
        return {"ai_probability": 0.5, "human_probability": 0.5, "verdict": "Unknown", "burstiness_score": 0.0}
