import json
import uuid
import asyncio
from typing import AsyncGenerator
from app.graph.workflow import app_graph
from app.schemas.request import HumanizeRequest

async def stream_humanize_workflow(request: HumanizeRequest) -> AsyncGenerator[str, None]:
    """
    Asynchronous generator that intercepts LLM tokens from LangGraph
    and yields them as Server-Sent Events (SSE).
    """
    req_id = str(uuid.uuid4())
    
    initial_state = {
        "request_id": req_id,
        "original_text": request.text,
        "document_type": request.document_type,
        "target_mode": request.target_mode,
        "target_tone": request.target_tone,
        "bypass_strength": request.bypass_strength,
        "status": "initialized",
        "claims": [],
        "facts": {},
        "entities": [],
        "constraints": [],
        "validation_errors": [],
        "revision_count": 0,
        "revision_history": [],
    }
    
    # We yield a starting event
    yield f"data: {json.dumps({'event': 'start', 'request_id': req_id})}\n\n"
    
    try:
        # astream_events captures internal node operations, including LLM token generation
        async for event in app_graph.astream_events(initial_state, version="v1"):
            kind = event["event"]
            
            # Intercept tokens generated by the ChatOllama LLM
            if kind == "on_chat_model_stream":
                chunk = event["data"]["chunk"]
                if hasattr(chunk, "content") and chunk.content:
                    yield f"data: {json.dumps({'event': 'token', 'text': chunk.content})}\n\n"
            
            # Capture the final state when the graph finishes
            elif kind == "on_chain_end" and event["name"] == "LangGraph":
                final_state = event["data"].get("output", {})
                if isinstance(final_state, dict) and "quality_score" in final_state:
                    # The graph has finished, emit the final scores
                    final_data = {
                        "event": "complete",
                        "quality_score": final_state.get("quality_score", 0),
                        "naturalness_score": final_state.get("naturalness_score", 0)
                    }
                    yield f"data: {json.dumps(final_data)}\n\n"
                    
    except Exception as e:
        yield f"data: {json.dumps({'event': 'error', 'message': str(e)})}\n\n"
